# Generated by Django 5.0.6 on 2024-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CofeeShopapp', '0001_newMigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('password', models.CharField(db_column='password', max_length=10)),
            ],
            options={
                'db_table': ' admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='barmaid',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('password', models.CharField(db_column='password', max_length=10)),
            ],
            options={
                'db_table': ' barmaid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('confirmation', models.IntegerField(db_column='confirmation')),
            ],
            options={
                'db_table': ' client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='insidetable',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('occupied', models.TextField(db_column='occupied')),
                ('places', models.IntegerField(db_column='places')),
                ('type', models.TextField(db_column='type')),
            ],
            options={
                'db_table': ' insidetable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(db_column='type')),
                ('price', models.IntegerField(db_column='price')),
                ('popularity', models.IntegerField(db_column='popularity')),
                ('alcool', models.IntegerField(db_column='alcool')),
                ('description', models.TextField(db_column='description')),
                ('image', models.IntegerField(db_column='image')),
                ('avaibility', models.IntegerField(db_column='avaibility')),
            ],
            options={
                'db_table': ' lunch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(db_column='type')),
                ('price', models.IntegerField(db_column='price')),
                ('popularity', models.IntegerField(db_column='popularity')),
                ('alcool', models.BooleanField(db_column='alcool')),
                ('description', models.TextField(db_column='description')),
                ('avaibility', models.BooleanField(db_column='avaibility')),
                ('photo', models.TextField(db_column='photo')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['price'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('MID', models.TextField(db_column='MID')),
                ('TABLE', models.IntegerField(db_column='TABLE')),
                ('price', models.IntegerField(db_column='price')),
                ('vip', models.TextField(db_column='vip')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='outsidetable',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('occupied', models.IntegerField(db_column='occupied')),
                ('places', models.IntegerField(db_column='places')),
            ],
            options={
                'db_table': ' outsidetable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(db_column='type')),
                ('price', models.IntegerField(db_column='price')),
                ('popularity', models.IntegerField(db_column='popularity')),
                ('alcool', models.IntegerField(db_column='alcool')),
                ('description', models.TextField(db_column='description')),
                ('image', models.IntegerField(db_column='image')),
                ('avaibility', models.IntegerField(db_column='avaibility')),
            ],
            options={
                'db_table': ' party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='vipclient',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('age', models.IntegerField(db_column='age')),
                ('CN', models.IntegerField(db_column='CN')),
                ('password', models.CharField(db_column='password', max_length=10)),
                ('confirmation', models.IntegerField(db_column='confirmation')),
                ('phone', models.TextField(db_column='phone')),
            ],
            options={
                'db_table': ' vipclient',
                'managed': True,
            },
        ),
    ]
