# Generated by Django 5.0.6 on 2024-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodTestModel',
            fields=[
                ('CID', models.CharField(db_column='CID', max_length=9, primary_key=True, serialize=False)),
                ('alk_phos', models.TextField(db_column='alk_phos')),
                ('hdl', models.TextField(db_column='hdl')),
                ('iron', models.TextField(db_column='iron')),
                ('creat', models.TextField(db_column='creat')),
                ('hb', models.TextField(db_column='hb')),
                ('urea', models.TextField(db_column='urea')),
            ],
            options={
                'db_table': 'bloodTest',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='doctormessages',
            field=models.TextField(db_column='doctormessages', default='null'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='doctorsanswer',
            field=models.TextField(db_column='doctorsanswer', default='null'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='latestreport',
            field=models.TextField(db_column='latestreport', default='null'),
        ),
    ]
